services:
  postgres:
    image: postgres:16
    container_name: covenant_postgres
    restart: always
    env_file:
      - .env  # Убедитесь что здесь .env, не credential.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - covenant-net

  app:
    build: .
    container_name: covenant_app
    depends_on:
      - postgres
    env_file:
      - .env  # Убедитесь что здесь .env, не credential.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - covenant-net

volumes:
  postgres_data:

networks:
  covenant-net: